src/objects/ZDocument_DesignLayout__c.object
<CustomObject>
    <label>ZDocument Design Layout</label>
    <nameField>
        <label>Design Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZDocument Design Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZDocument_Setup__c.object
<CustomObject>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referred_Column__c</fullName>
        <inlineHelpText>Actual Column Names</inlineHelpText>
        <label>Referred Column</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Indexed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Type</fullName>
                </value>
                <value>
                    <fullName>Updated Date</fullName>
                </value>
                <value>
                    <fullName>Form</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referred_DocType__c</fullName>
        <label>Referred DocType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDOT</fullName>
                </value>
                <value>
                    <fullName>3500</fullName>
                </value>
                <value>
                    <fullName>DOSE</fullName>
                </value>
                <value>
                    <fullName>ENRLC</fullName>
                </value>
                <value>
                    <fullName>PIRM</fullName>
                </value>
                <value>
                    <fullName>REFR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZDocument_DesignLayout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZDocument Design Layout</label>
        <referenceTo>ZDocument_DesignLayout__c</referenceTo>
        <relationshipLabel>ZDocument Setup</relationshipLabel>
        <relationshipName>ZDocument_Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ZDocument Setup</label>
    <nameField>
        <label>ZDocument Column/DocType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZDocument Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/zLDSDocumentSetController_Test.cls
/*******************************************************************************************
* @Author      : Vikas Reddy
* @Date        : 8/29/2017
* @Description : The zLDSDocumentSetController_Test is used for UnitTesting and code-coverage the zLDSDocumentSetController class.
* @Apex Class  : zLDSDocumentSetController
*
* Modification Logs:
* -----------------------------------------------------------------------------------
* Developer               Date                    Description
* ---------------        ----------             -------------------------
* Vikas Reddy            08/29/2017               Original Version
*********************************************************************************************/

@isTest
private class zLDSDocumentSetController_Test {
   @isTest
   static void TestUnitTest(){
        ZDocument_DesignLayout__c design = new ZDocument_DesignLayout__c(Name = 'Case Layout');
        Insert design;

        List<ZDocument_Setup__c> zDocSetList = new List<ZDocument_Setup__c>();        
        Id RTId = Schema.SObjectType.ZDocument_Setup__c.getRecordTypeInfosByName().get('zDocument Columns').getRecordTypeId();
                
        ZDocument_Setup__c setup1 = new ZDocument_Setup__c();
        setup1.Name = 'Indexed';
        setup1.RecordTypeId = RTId;
        setup1.ZDocument_DesignLayout__c = design.id;
        setup1.Referred_Column__c = 'Indexed';
        setup1.Sort_Order__c = 1;
        setup1.IsRequired__c = true;        
        zDocSetList.add(setup1);
        
        ZDocument_Setup__c setup2 = new ZDocument_Setup__c();
        setup2.Name = 'Updated';
        setup2.RecordTypeId = RTId;
        setup2.ZDocument_DesignLayout__c = design.id;
        setup2.Referred_Column__c = 'Updated';
        setup2.Sort_Order__c = 2;
        setup2.IsRequired__c = true;        
        zDocSetList.add(setup2);
        
        Id DocRTId = Schema.SObjectType.ZDocument_Setup__c.getRecordTypeInfosByName().get('zDocument Types').getRecordTypeId();
        
        ZDocument_Setup__c setup3 = new ZDocument_Setup__c();
        setup3.Name = 'HDOT';
        setup3.ZDocument_DesignLayout__c = design.id;
        setup3.RecordTypeId = DocRTId;
        setup3.Referred_DocType__c = 'HDOT';
        setup3.Sort_Order__c = 1;
        setup3.IsRequired__c = true;        
        zDocSetList.add(setup3);
        
        ZDocument_Setup__c setup4 = new ZDocument_Setup__c();
        setup4.Name = 'REFR';
        setup4.ZDocument_DesignLayout__c = design.id;
        setup4.RecordTypeId = DocRTId;
        setup4.Referred_DocType__c = 'REFR';
        setup4.Sort_Order__c = 2;
        setup4.IsRequired__c = true;
        zDocSetList.add(setup4);
        
        ZDocument_Setup__c setup5 = new ZDocument_Setup__c();
        setup5.Name = 'Rejected';
        setup5.ZDocument_DesignLayout__c = design.id;
        setup5.RecordTypeId = RTId;
        setup5.Referred_Column__c = 'Rejected';
        setup5.Sort_Order__c = 3;
        setup5.IsRequired__c = true;
        zDocSetList.add(setup5);
        
        Insert zDocSetList;
       
        Test.StartTest();
        zLDSDocumentSetController zLDS = new zLDSDocumentSetController();
		zLDS.layoutId = design.id;
        zLDS.getLayoutJSON();
        Test.StopTest();
   }
}